%!PS-Adobe-3.0
%%BoundingBox: 0 0 860 1500

% Choices what to selectively cut.
/print-toppanel true def     % The laser and rotating mirror are mounted here.
/print-sidepanels true def   % Side panels framing device.
/print-siderails true def    % The rails the sled is riding on.
/print-front-back true def   % front and back parts of the case
/print-sled true def         % The sled moving the PCB along

% Suggested to cut on thinner material (1mm acrylic)
/print-pcbframe false def

% There are two parts to print, each of them fits on a 30cmx30cm acrylic
% sheet. Choose part 0 or part 1 here.
% TODO: this needs to be done better. For instance, is there a way to set
% a dictionary value from the command line ?
/print-part 0 def

/mm { 72 25.4 div mul } bind def

/acrylic-t 3 mm def   % Material thickness.
/screw-r 3.1 mm 2 div def
/rod-r 4.7 mm 2 div def
/finger-len 11 mm def

/pcb-w-mm 100 def
/pcb-h-mm 160 def

/pcb-w pcb-w-mm mm 2 mm add def
/pcb-h pcb-h-mm mm 2 mm add def

/bed-w pcb-w 16 mm add def    % (3 mm in the rails + 5 mm) on each side
/bed-h pcb-h 10 mm add def

/bed-drive-screw-w 3.4 mm def  % thickness of driving screw
/bed-drive-screw-r 10.5 2 div mm def  % outer radius of nut driving the thing.

/bed-drive-pos bed-h 2 div def  % where the drive position relative from back.
/bed-drive-w 29 mm def
/bed-drive-h bed-drive-screw-r 2 mul 5 mm add def

% derived from above.
/bed-pcb-off-w bed-w pcb-w sub 2 div def
/bed-pcb-off-h bed-h pcb-h sub 2 div def

/bed-slide-high 15 mm def
/slide-hole-count 4 def

/stepper-width 0.8 25.4 mm mul def  % nema8

% TODO: calculate laser slot distance from angle, pcb-w, laser height etc.
/laser-slot-distance 160 mm stepper-width add def
/laser-slot-h 10 mm def
/laser-slot-w pcb-w 2 mm add def

/rot-mirror-high 33 mm 2 div def  % center of the laser
/rot-mirror-w 44 mm def
/rot-mirror-h 60 mm def
/rot-mirror-diameter 30 mm def

% The down mirror is elevated above the top plate, so we need the acrylic
% thickness to be on the same level as the rot mirror that is mounted on
% the top plate.
/down-mirror-high rot-mirror-high acrylic-t add def
/down-mirror-w 10 mm def
/down-mirror-t 4.5 mm def

% Given that we cover 60 degrees, we cover 2 * sin(30) times radius in
% horizontal direction, i.e. radius == pcb-w. We want to use a little less of
% the range to have space for synchronization.
/arc-radius pcb-w 20 mm add def

% actually, we should calculate the laser slot from the mirror center which
% should be placed as much back as we want. But for version #1, we already
% have set up the laser-slot-distance and the grooves and fingers, so let's go with
% that first.
/mirror-center-mount-from-slot
    arc-radius rot-mirror-high sub bed-slide-high sub
    rot-mirror-diameter add def

% We want to be at least half pcb sled longer so that we are supported
% at center of gravity.
/inner-device-len laser-slot-distance bed-h 2 div add def
/inner-device-high bed-slide-high 2 mul acrylic-t add def

/mirror-holder-width 20 mm def  % width of the 45 degree down mirror holder
/mirror-holder-r mirror-holder-width 2 div def
/mirror-holder-high down-mirror-high mirror-holder-r add def

% -- variables to place properly between cuts
% distance between different cuts
/cut-dist 1 mm def
/side-cut-distance inner-device-high 2 mul mirror-holder-high add cut-dist add acrylic-t add def

% Linewidth doesn't do anything to the DXF output, it just makes it easier
% to manually inspect in the PostScript viewer.
0.5 setlinewidth

% dx dy amount
/perpendicular {
	5 dict begin
       /thick exch  def
       /dy exch def
       /dx exch def
       /len dx dx mul dy dy mul add sqrt def
       /fraction thick len div def  % fraction of amount that is perpendicular
       dy fraction mul neg dx fraction mul rlineto
       end
} def

% dx dy thick
/orth-segment {
	3 dict begin
       /thick exch  def
       /dy exch def
       /dx exch def
       dx dy thick perpendicular
       dx dy rlineto
       dx dy thick neg perpendicular
       end
} def

/finger-groove-rlineto {
    9 dict begin
    /thick exch def
    /dy exch def
    /dx exch def
    /len dx dx mul dy dy mul add sqrt def
    /factor acrylic-t len div def  % perpendicular thing.
    /segments
         len finger-len sub  % we want one finger len at the end
	 finger-len 2 mul    % number of low and up segments
	 div floor cvi def
    /extra-fraction len finger-len sub
         segments finger-len 2 mul mul sub len div 2 div def
    dx extra-fraction mul dy extra-fraction mul rlineto
    /sdx dx finger-len len div mul def
    /sdy dy finger-len len div mul def
    1 1 segments {
	pop
	sdx sdy rlineto
	sdx sdy thick orth-segment
    } for
    sdx sdy rlineto  % one extra bottom segment.
    dx extra-fraction mul dy extra-fraction mul rlineto
    end
} def

% dx dy
/finger-rlineto {
    acrylic-t neg finger-groove-rlineto
} def

/groove-rlineto {
    2 dict begin
    /dy exch def
    /dx exch def
    dx dy acrylic-t neg perpendicular
    dx dy acrylic-t finger-groove-rlineto
    dx dy acrylic-t perpendicular
    end
} def

% xt yt
/finger-lineto {  % need: (xt - x) (yt - y)
    currentpoint  % xt yt x y
    3 -1 roll exch sub  % xt yt x y -> xt x y yt -> xt x yt y -> xt x (yt - y)
    3 1 roll sub  % dy dx
    exch
    finger-rlineto
} def

/groove-lineto {  % need: (xt - x) (yt - y)
    currentpoint  % xt yt x y
    3 -1 roll exch sub  % xt yt x y -> xt x y yt -> xt x yt y -> xt x (yt - y)
    3 1 roll sub  % dy dx
    exch
    groove-rlineto
} def

% dx dy  TODO: this is hacky.
/slot-rlineto {
    gsave
    1 0 0 setrgbcolor   % inside kerf correction.
    9 dict begin
    /dy exch def
    /dx exch def
    /len dx dx mul dy dy mul add sqrt def
    /segments
         len finger-len sub  % we want one finger len at the end
	 finger-len 2 mul    % number of low and up segments
	 div floor cvi def
    /extra-fraction len finger-len sub
         segments finger-len 2 mul mul sub len div 2 div def
    dx extra-fraction mul dy extra-fraction mul rmoveto
    /sdx dx finger-len len div mul def
    /sdy dy finger-len len div mul def
    1 1 segments {
	pop
	sdx sdy rmoveto
	currentpoint
	acrylic-t sdy box
	moveto 0 sdy rmoveto
    } for
    end
    grestore
} def

% x y r
/circle {
    1 dict begin
    /crr exch def
    moveto
    currentpoint
    crr 0 rmoveto
    crr 0 360 arc
    end
} def

% r is the outer radius.
% n r
/n-polygon {
    gsave
    currentpoint translate
    3 dict begin
    /r exch def
    /n exch def
    /angle 360 n div def
    r 0 moveto
    1 1 n {
	dup
	angle mul cos r mul
	exch
	angle mul sin r mul
	lineto
    } for
    closepath stroke
    end
    grestore
} def

/screw {
    screw-r circle
} def

/rod {
    rod-r circle
} def

/box {
  2 dict begin
  /h exch def
  /w exch def

  w 0 rlineto
  0 h rlineto
  w neg 0 rlineto
  0 h neg rlineto
  closepath stroke
  end
} def

% w h radius
/rounded-corner-box {
   3 dict begin
   /radius exch def
   /height exch def
   /width exch def

   currentpoint
   gsave
   translate
   0 radius add 0 moveto
   width radius sub 0 lineto
   width radius sub 0 radius add radius -90 0 arc

   width height radius sub lineto
   width radius sub height radius sub radius 0 90 arc

   0 radius add height lineto
   0 radius add height radius sub radius 90 180 arc

   0 0 radius add lineto
   0 radius add 0 radius add radius 180 270 arc
   closepath stroke
   grestore
   end
} def

% Boolean if outline should be printed
% bool x y
/rot-mirror-footprint {
    gsave
    translate
    0 0 moveto
    currentpoint 7 mm circle
    41.6 mm 2 div 40 mm screw
    41.6 mm 2 div neg 40 mm screw
    41.6 mm 2 div -18.5 mm screw
    41.6 mm 2 div neg -18.5 mm screw
    stroke

    48 mm 2 div neg -24 mm translate

    % should we print the outline ?
    { 0 0 moveto 48 mm 68 mm box  } if % cuts the outer of the mirror

    48 mm 15 mm sub 2 div 0 moveto 15 mm 5 mm box
    stroke
    grestore
} def

% (text)
/center-show {
    dup stringwidth pop 2 div neg 0 rmoveto
    show
} def

/slide-holes {
    inner-device-len slide-hole-count div 2 div
    inner-device-len slide-hole-count div
    inner-device-len {
	bed-slide-high 2 div rod
    } for
    stroke
} def

%---- end help procedures, start parts.

/part-toppanel {
    % bottom area
    newpath
    0 0 moveto

    % up to mirror slot
    laser-slot-distance mirror-holder-r sub 0 groove-lineto

    % mirror slot width
    mirror-holder-width 0 rlineto

    % to the end on the right.
    inner-device-len 0 groove-lineto

    % up. Either straight line or circular cut
    false {
       0 bed-w rlineto
    } {
       inner-device-len bed-w 2 div
       bed-w 2 div 10 mm sub
       270 90 arcn
       inner-device-len bed-w lineto
    } ifelse

    laser-slot-distance mirror-holder-r add bed-w groove-lineto
    mirror-holder-width neg 0 rlineto

    0 bed-w groove-lineto
    0 0 groove-lineto
    closepath stroke

    % mounting holes for mirror
    false  % do not cut outline
    laser-slot-distance mirror-center-mount-from-slot sub bed-w 2 div rot-mirror-footprint

    % Laser slot
    laser-slot-distance laser-slot-h 2 div sub bed-w laser-slot-w sub 2 div moveto
    laser-slot-h laser-slot-w 3 mm rounded-corner-box

    gsave
      0 1 0 setrgbcolor
      laser-slot-distance laser-slot-h 2 div add bed-w 2 div moveto
      90 rotate
      /Courier findfont 5 mm scalefont setfont
      0 -5 mm rmoveto
      gsave (github/hzeller) center-show grestore
      /Courier findfont 22 mm scalefont setfont
      0 -18 mm rmoveto
      gsave (LDGraphy) center-show grestore
   grestore
} def

/part-sidepanel {
    newpath
    % bottom parth
    0 0 moveto
    inner-device-len 0 lineto

   % up right side (back)
   1 dict begin
      /finger-len 4 mm def
     inner-device-len inner-device-high groove-lineto
   end

    % to start of mirror-holder
    inner-device-len laser-slot-distance sub mirror-holder-r add inner-device-high finger-lineto

    % Notch for mirror
    0 down-mirror-high rlineto  % center of 45 degree mirror
    inner-device-len laser-slot-distance sub inner-device-high down-mirror-high add mirror-holder-r 0 180 arc

    % end of mirror holder, down to top panel again.
    inner-device-len laser-slot-distance sub mirror-holder-r sub inner-device-high lineto

    0 inner-device-high finger-lineto

   % TODO: this does not align properly yet, because we do three notches here
   % but the front only has one.
   % down left side (front)
   1 dict begin
      /finger-len 4 mm def
      0 0 groove-lineto
    end
    closepath stroke

    gsave
      inner-device-len laser-slot-distance sub  % we go from the back
      inner-device-high down-mirror-high add translate
      45 rotate
      down-mirror-w 2 div neg down-mirror-t 2 div neg moveto down-mirror-w down-mirror-t box
      stroke
   grestore

   slide-holes
   gsave 0 bed-slide-high 3 mm add translate slide-holes grestore
} def

/part-slide-rail {
    0 0 moveto inner-device-len bed-slide-high box
    slide-holes
    stroke
} def

/part-back {
   newpath
   0 0 moveto
   bed-w 0 lineto

   1 dict begin
      /finger-len 4 mm def
      bed-w inner-device-high finger-lineto   % up
   end

   bed-w neg 0 finger-rlineto       % top accross

   1 dict begin
      /finger-len 4 mm def
     0 0 finger-lineto   % down
   end

   closepath stroke

   % drive screw and nema8 mount
   gsave
   1 0	 0 setrgbcolor
   bed-w 2 div 10 mm translate
   0 0 16 mm 2 div circle stroke
   7.7 mm 7.7 mm 1 mm circle stroke
   -7.7 mm 7.7 mm 1 mm circle stroke
   -7.7 mm -7.7 mm 1 mm circle stroke
   7.7 mm -7.7 mm 1 mm circle stroke
   grestore
} def

% TODO: this does not align properly yet.
/part-front {
   newpath
   0 0 moveto
   bed-w 0 lineto

   1 dict begin
      /finger-len 4 mm def
     bed-w bed-slide-high finger-lineto   % up
   end

   bed-w neg 0 rlineto

   1 dict begin
      /finger-len 4 mm def
      0 0 finger-lineto   % down
   end

   closepath stroke

   % drive screw
   bed-w 2 div 10 mm rod-r circle stroke
} def

/part-pcb-frame {
  % Frame to place PCB in.
  gsave
   % Outer frame
   acrylic-t 0 moveto bed-w acrylic-t 2 mul sub bed-h box

   % Inner frame
   bed-pcb-off-w bed-pcb-off-h translate
   0 0 moveto pcb-w pcb-h box

   % Corner reliefs
   0 0 0.8 mm circle
   pcb-w 0 0.8 mm circle
   0 pcb-h 0.8 mm circle
   pcb-w pcb-h 0.8 mm circle
   stroke

   0 1 0 setrgbcolor
   pcb-w 0 translate  % bottom left corner as origin for measurements
   /Courier findfont 2.5 mm scalefont setfont
   0 1 pcb-w-mm {
       1 dict begin
       /i exch def
       i mm neg 1 mm moveto
       i 5 mod 0 eq { i 10 mod 0 eq { -7 mm } { -4.5 mm } ifelse } { -3 mm } ifelse 0 exch rlineto stroke
       i 10 mod 0 eq {
	   gsave
           i mm neg 0.5 mm sub -4.5 mm translate 90 rotate
	   0 0 moveto
	   i 10 div cvi 5 string cvs show
	   grestore
       } if
      end
   } for
   0 1 pcb-h-mm {
       1 dict begin
       /i exch def
       i mm -1 mm exch moveto
       i 5 mod 0 eq { i 10 mod 0 eq { 7 mm } { 4.5 mm } ifelse } { 3 mm } ifelse 0 rlineto stroke
       i 10 mod 0 eq {
	   gsave
           i mm 0.5 mm add 4.5 mm exch translate 90 rotate
	   0 0 moveto
	   i 10 div cvi 5 string cvs show
	   grestore
       } if
       end
   } for
  grestore
} def

/subpart-drive-holder {
  gsave
  0 0 moveto
  bed-drive-h 0 rlineto
  0 bed-drive-w rlineto
  bed-drive-h neg 0 rlineto
  0 bed-drive-w neg finger-rlineto
  stroke
  bed-drive-h bed-drive-w 2 div bed-drive-h 1.2 div circle stroke
  grestore
} def

/part-sled {
  1 dict begin
  /finger-len 4 mm def

  0 0 moveto bed-h bed-w box  % the sled

  gsave
    bed-drive-pos bed-drive-screw-w 2 div sub acrylic-t sub
    bed-w 2 div bed-drive-w 2 div sub moveto
    0 bed-drive-w slot-rlineto stroke
  grestore

  gsave
    bed-drive-pos bed-drive-screw-w 2 div add
    bed-w 2 div bed-drive-w 2 div sub moveto
    0 bed-drive-w slot-rlineto stroke
  grestore

  gsave
  bed-h cut-dist add acrylic-t add 0 translate subpart-drive-holder
  0 bed-drive-w cut-dist add translate subpart-drive-holder
  0 bed-drive-w cut-dist add translate

  0 0 moveto bed-drive-screw-r 2 mul 2 mm add bed-drive-w 1.2 mul box
  bed-drive-screw-r 1 mm add bed-drive-w 1.2 mul 2 div translate
  0 0 moveto
  360 12 div rotate
  6 bed-drive-screw-r n-polygon stroke
  grestore
  end
} def

%% Assembly

acrylic-t cut-dist add cut-dist translate

print-sidepanels {
  % Two side-panels, turned around and printed in place
  part-sidepanel
  gsave inner-device-len side-cut-distance translate 180 rotate part-sidepanel grestore
  % move up
  0 side-cut-distance cut-dist add translate
} if

print-siderails {
  part-slide-rail
  0 bed-slide-high cut-dist add translate part-slide-rail
  0 bed-slide-high cut-dist add translate part-slide-rail
  0 bed-slide-high cut-dist add translate part-slide-rail
  0 bed-slide-high cut-dist add translate
} if

print-toppanel {
  0 acrylic-t translate   % to have space for the fingers
  0 0 moveto part-toppanel

  true {
     % extra raiser board for the mirror
    gsave
    inner-device-len 10 mm sub 49 mm translate
    true  % cut outline
    0 0 rot-mirror-footprint stroke
    grestore
  } if

  0 bed-w 2 acrylic-t mul add translate
} if

print-front-back {
  0 0 moveto part-front stroke % front-piece
  gsave bed-w acrylic-t 2 mul add cut-dist add 0 translate
        part-back stroke grestore % back piece
  0 inner-device-high acrylic-t add cut-dist add translate
} if

print-sled {
  part-sled
  0 bed-w cut-dist add translate
} if

print-pcbframe {
  gsave
  0 bed-w acrylic-t sub translate -90 rotate
  part-pcb-frame
  % extra raiser board for the mirror. Use empty space in the area in the
  % middle. Since that often needs to be a thinner shim, this is perfect
  % as this is typically printed on 1mm
  40 mm 40 mm translate
  true  % cut outline
  0 0 rot-mirror-footprint stroke
  grestore
  0 bed-w acrylic-t 2 mul sub cut-dist add translate
} if

stroke
showpage
